# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: ZN-M2

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: 'Extra config lines. Separate multiple lines with \n.'
        required: false
        type: string
      TEST:
        description: 'Generate the final config only, without compiling firmware.'
        default: 'false'
        required: false
        type: boolean

permissions: write-all

jobs:
  build:
    name: ZN-M2
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ZN-M2-WIFI-NO
      WRT_THEME: aurora
      WRT_NAME: OWRT
      WRT_SSID: OWRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: none
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      WRT_BRANCH: main
      WRT_SOURCE: VIKINGYFY/immortalwrt
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST}}
